language: python
sudo: false
dist: xenial

os:
    - windows
    - linux


cache: pip

python:
    - "3.6"
    - "3.7"


matrix:
    include:  # Workaround for python 3.7.
        - python: "3.7"
          dist: xenial
          sudo: required

    fast_finish: true
    allow_failures:
        - os: windows  # allow failure on Win until Travis-Win supports python.
#        - python: "3.7"  # Travis CI not supporting 3.7 yet


install:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt


# command to run tests
script:
    - pytest --cov
    - coverage xml
    - python-codacy-coverage -r coverage.xml

after_success: coveralls
